apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf  # Menyuntikkan hanya file nginx.conf ke dalam path yang sesuai
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config  # Nama ConfigMap yang sudah dibuat sebelumnya
      - name: html
        gitRepo:
          repository: "https://github.com/mahendra1231/nginx-deployment.git"
          revision: "main"
          directory: "web-content"
